apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: flask-app
type: Opaque
stringData:
  DB_USER: appuser
  DB_PASSWORD: apppass
  SECRET_KEY: super-secret-key
  POSTGRES_USER: appuser
  POSTGRES_PASSWORD: apppass